### ISSUE TITLE
odd behavour on windows

### ISSUE THREAD

**Issue by pm100** [tui-rs-revival/ratatui#166]
I reported this bug to tui-textarea https://github.com/rhysd/tui-textarea here https://github.com/rhysd/tui-textarea/issues/14

They support tui and ratatui

In their demo app (very simple) the keystrokes are duplicated on windows. It works fine using tui but fails 100% using ratatui

here is gif of the behavior

![minbug](https://user-images.githubusercontent.com/489231/236242601-e029771e-f9bd-44d9-9a39-a30f60a28572.gif)

**Comment by mindoodoo** [comment]
Go checkout #120 which brought up the same issue, essentially in windows you will need to match against the specific `KeyPressed ` event, otherwise your code will also be triggered by `KeyUp` event (don't quote me on the event type names tho). All the examples were fixed in order to handle this explicitly in #129.

So without checking out there example, that's most likely what's happening.

**Comment by pm100** [comment]
but it worked fine with tui, so ratatui introduced a breaking change

**Comment by Eyesonjune18** [comment]
This is a `crossterm` issue

**Comment by mindoodoo** [comment]
@pm100 I wouldn't be able to tell you without looking more into it why it changed, but this was most likely introduced by a `crossterm` update. However, this isn't a bug with `ratatui` nor `crossterm` and more a bug with the particular example you're looking at.

There's an [open pr](https://github.com/crossterm-rs/crossterm/pull/778) over on the crossterm repo aiming to make the `KeyUp` event opt-in, but hasn't been merged yet.

Since this isn't really a bug with `ratatui`, I'll close this for now.

**Comment by pm100** [comment]
fyi - caused by https://github.com/crossterm-rs/crossterm/pull/745
