### ISSUE TITLE
Enable setting the underline color

### ISSUE THREAD

**Issue by Nogesma** [tui-rs-revival/ratatui#308]
## Problem
There is a nonstandard ansi escape code that allows setting the underline color.

This is done with the code `58`. it uses the same arguments as the `38` and `48` codes do for settings their colors.
The underline color can be reset with the code `59`.

See [kitty documentation](https://sw.kovidgoyal.net/kitty/underlines/) for more info.

This is implemented in at least kitty, wezterm, alacritty, gnome terminal and konsole.

## Solution
Allow this to be possible
```rust
Style::default().underline(Color::Blue).add_modifier(Modifier::UNDERLINE),
```

I can make a PR if needed.

**Comment by orhun** [comment]
Sounds like a nice feature, feel free to submit a PR! 🐻

**Comment by Nogesma** [comment]
I've noticed only crossterm supports setting the underline color, termion and termwiz do not. 
Is putting it behind the crossterm feature flag the option you prefer?

**Comment by joshka** [comment]
The proposed function name will conflict with https://github.com/tui-rs-revival/ratatui/pull/289 which adds an `underline()` method to Style via the Stylize trait. Perhaps `underline_color`? Could there likely be other extended escape codes that might be added in the future?

It would be nice to generally keep feature parity between the backends, so perhaps submitting PRs to termion / termwiz for this feature would be a good in addition to feature flagging behind the crossterm flag here.

We recently made it possible to build Ratatui with all backend feature flags enabled together in order to make it easier to develop changes to backends without having to disable / enable features, so the implementation of this might end up being a no-op on the other backends?

**Comment by Nogesma** [comment]
I've renamed it it to `underline_color`. 

I am not really familiar with any of the non-basic escape codes, so I don't really know if some other codes would need to be added in the future. 

I can make a issue on the termion/termwiz repositories, but I am not really interested in making a PR. 

For now the implementation is a no-op for the other backends.

I just submitted a PR (#310).

**Comment by mindoodoo** [comment]
@Nogesma Yes if you could open up an issue on the `Termion` and `Wezterm` backends, it would be great as I would have to agree with @joshka that feature parity accross backends is quite important.

**Comment by Nogesma** [comment]
I submited an issue for termwiz, but I don't have a gitlab account on redox-os' gitlab. I would prefer to not have to create one, if someone can submit an issue there?
