### ISSUE TITLE
Marker to draw shapes without gaps in the vertical direction on canvas

### ISSUE THREAD

**Issue by BoolPurist** [tui-rs-revival/ratatui#82]
## Problem

When I draw lines in vertical direction on a canvas with block as marker  then I have gaps between the blocks. 
In my view this in not consistent because  a line has no gaps horizontall

Here is a code example on a [gist](https://gist.github.com/BoolPurist/89c9ba1f001e8874dccf9eaa61071761) of mine.
This gist produces the following output onto the terminal, see picture under additional context.

In the picture the red line is fine, however the blue line in the vertical direction produces gaps which I do not want.

## Solution

-  Implement Marker::Block in a way that there are no vertical gaps in a vertical line for example.

## Alternatives

- Implement a new marker like Block however it does not produce gaps in horizontal or vertical direction. 

## Additional context

For the example I have used this respo as tui dependency with the main branch on the commit 73f7f16298b75e015e0e80c7c82208b5b420e78a

![vertical_line_with_gaps](https://user-images.githubusercontent.com/57603453/222896894-53e0375f-3256-4e24-8494-68ecec5c1d4d.png)

**Comment by joshka** [comment]
https://github.com/tui-rs-revival/ratatui/blob/main/src/widgets/canvas/mod.rs#L265 seems like the issue:
```
symbols::Marker::Block => Box::new(CharGrid::new(width, height, '▄')),
```
It's possible that this should be:
```
symbols::Marker::Block => Box::new(CharGrid::new(width, height, '█')),
```
But it might be nicer to fix this so that the size of the block or bar can be configured e.g. using block and bar from [`symbols`](https://github.com/tui-rs-revival/ratatui/blob/main/src/symbols.rs)
```
pub mod block {
    pub const FULL: &str = "█";
    pub const SEVEN_EIGHTHS: &str = "▉";
    pub const THREE_QUARTERS: &str = "▊";
    pub const FIVE_EIGHTHS: &str = "▋";
    pub const HALF: &str = "▌";
    pub const THREE_EIGHTHS: &str = "▍";
    pub const ONE_QUARTER: &str = "▎";
    pub const ONE_EIGHTH: &str = "▏";
```
or:
```
pub mod bar {
    pub const FULL: &str = "█";
    pub const SEVEN_EIGHTHS: &str = "▇";
    pub const THREE_QUARTERS: &str = "▆";
    pub const FIVE_EIGHTHS: &str = "▅";
    pub const HALF: &str = "▄";
    pub const THREE_EIGHTHS: &str = "▃";
    pub const ONE_QUARTER: &str = "▂";
    pub const ONE_EIGHTH: &str = "▁";
```

And it could be even worth just allowing any character as a marker (draw lines of emoji for instance)

Fixing this would probably change the way that anything that uses this renders. [Usages in github projects](https://github.com/search?q=language%3Arust+Marker%3A%3ABlock&type=code) has about 34 places to check the impact of.

A simple obvious fix would be to add a Marker::Bar for the existing half height bar, which allows this to properly render for your case.
